let adjective = "mischievous";
let noun = "unicorn";
let verb = "dancing";
let place = "cotton candy cloud";
let adjective2 = "rainbow-colored";
let noun2 = "stardust cupcakes";
let firstStory = "Once upon a time, there was a(n) " + adjective + " " + noun + " who loved to eat " + noun2 + ". The " + noun + " lived in a " + place + " and had " + adjective2 + " nostrils that blew fire when it was " + verb + ".";
console.log("First story: " + firstStory);
adjective = "anxious";
noun = "mermaid";
verb = "sneezing";
place = "bubble bath ocean";
adjective2 = "glittery";
noun2 = "jellyfish tacos";
let secondStory = "Once upon a time, there was a(n) " + adjective + " " + noun + " who loved to eat " + noun2 + ". The " + noun + " lived in a " + place + " and had " + adjective2 + " nostrils that blew fire when it was "+ verb + ".";
console.log("Second story: " + secondStory);